name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --keep-going --verbose

  build:
    name: Build linux-lava for x86_64-linux
    runs-on: ubuntu-latest
    steps:
      # credits to https://github.com/easimon/maximize-build-space/issues/45
      - name: Remove unneeded packages to maximise build space
        shell: bash
        run: |
            df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            df -h
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#linux-lava
