name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220930_89ca75c/install
          extra_nix_config: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --keep-going --verbose

  build:
    name: Build linux-lava for x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220930_89ca75c/install
          extra_nix_config: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#linux-lava

  build-nix:
    runs-on: ubuntu-latest
    name: Build nixUnstable for aarch64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dbhi/qus/action@main
        with:
          targets: arm aarch64
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220930_89ca75c/install
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#packages.aarch64-linux.nixUnstable

  build-img:
    runs-on: ubuntu-latest
    name: Build caramel-img for aarch64-linux
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dbhi/qus/action@main
        with:
          targets: arm aarch64
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220930_89ca75c/install
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#packages.aarch64-linux.caramel-img
      - uses: actions/upload-artifact@v3
        with:
          name: caramel-sdimage
          path: result/sd-image/*
