name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: Check flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --keep-going --verbose

  build:
    name: Build linux-lava for x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#linux-lava
