name: Build images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build caramel-img
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dbhi/qus/action@main
        with:
          targets: arm aarch64
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.12.0pre20220930_89ca75c/install
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: lava
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build -L .#packages.aarch64-linux.caramel-img
      - uses: actions/upload-artifact@v3
        with:
          name: caramel-sd-image
          path: result/sd-image/*
